### ISSUE TITLE
Card Rating Uses Turn Last Seen

### ISSUE THREAD

**Issue by moonymachine** [LazarQt/LimitedPower.DraftHelperSync#1]
I saw on Reddit where you said you had written the tool to show pick rate, but right now the algorithm uses the turn the card is usually seen last. The data for the turn the card is taken is available in your model. These two data points are often similar, but can be quite different. For example, a card like Pithing Needle has a low pick rate, but is not likely to wheel. I assume because someone may take this rare to put in their Standard constructed sideboard, which has nothing to do with the draft.
![screenshot745](https://user-images.githubusercontent.com/8032848/140167510-2b15ab70-fa9d-45f7-8c4f-9fbfe1b2976a.png)
Or, a card like Morkrut Behemoth. It also has a disparity in pick order, and whether you are likely to see it again. I think this is because people don't pick the card highly, but it's still a fairly good card that is less likely to wheel around the table. Part of the reason for picking it later is because it's common, and you don't need a lot of them, and you may see more than one.
![screenshot746](https://user-images.githubusercontent.com/8032848/140167774-ac90f2c0-aa12-439d-bfb9-a957796d68df.png)
I think using AvgPick instead of AvgSeen would provide more relevant pick order data for drafting.

Also, this is just a preferential, readability issue, but I think the formula in TransformRating would be more readable as:
(int) Math.Round(10 - 10 * (value - min) / (max - min), 0, MidpointRounding.AwayFromZero);

**Comment by LazarQt** [comment]
I just updated the methodology to determine the pick order because I wasn't happy with the initial solution.

In the first iteration (currently in use) I simply took the AvgSeen data point.
The trouble here is, ignoring the fact that AvgPick would be better as you pointed out, that some unplayable cards show up very high in the rankings because people rare draft often.

In the second iteration, I looked at the highest and lowest win rates and used these data points as the range of possible pick orders and aligned them with the win rates of the individual cards. 
Now the problem was that there were great cards for the colors you were already in, but because not all colors are of equal strength (for example blue and black in MID) I would often hedge during a draft even though I had perfectly reasonable cards I could've taken.

What I'm doing now is: I use the same formula as in iteration #2, but limit it to the respective colors. For example: If a red card has a 70% win rate but the best card overall has a 80% win rate, it would still show up as a "10" instead of a lower pick rate grade because it's the best card in that color.

Since you are the very first person to open an issue I thought I'd ask what you think of this. I haven't tested it yet (waiting for new set right now) but in case you have a better idea I might implement something else. At the very least, I will update the configuration so everyone can chose their preferred method (AvgPick or my new logic or whatever else).

What do you think?

Cheers

**Comment by LazarQt** [comment]
I implemented all three, it can be switched by modifying the config file, see documentation.
