### ISSUE TITLE
Cannot find .dll.config file or bin folder

### ISSUE THREAD

**Issue by robertfoster550** [LazarQt/LimitedPower.DraftHelperSync#3]
Hi. I'm sorry to bug you with such a simple issue - I'm sure I am missing something dumb. I'm trying to follow the ReadMe: I downloaded the latest release (Beta 0.2.1), unzipped it, and... I just cannot find any of the files you talk about. I cannot find the .dll.config. I cannot find the .exe. Looking at the images you have, I see that inside the LimitedPower.DraftHelperSync folder should be a bin folder, which I also cannot see. I've included an image of the files I do have in this main folder. Maybe you can point out what I'm missing? And if it is something dumb and simple hopefully it can help make the ReadMe usable by 5-year-olds. 

Thanks a bunch for any help you can provide!

![DraftHelper](https://user-images.githubusercontent.com/54109737/154796618-1751f082-84fc-469a-9f52-6ffaa8e882a7.png)

**Comment by LazarQt** [comment]
Hi

It seems you downloaded the source files.

Make sure to download the .zip that is NOT named "source files", "binary" (or similar) and try again.
Should look like this:
https://i.imgur.com/rw6DTNs.gif

I hope this helps, otherwise just comment again and I'll try to make it clearer or do a whole video.
Sorry for the wait!

Cheers

**Comment by robertfoster550** [comment]
Ah, yes, that was it. Everything is looking more like I expected now. Thanks for the help!
